spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?useUnicode=true&serverTimezone=Asia/Seoul&sslMode=REQUIRED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yerong
    password: 12345678
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: info
